/*
You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404
*/
const express = require("express");
const bodyparser = require("body-parser");
const app = express();
const port = 3000;
app.listen(port,() => {
    console.log(`Example app listening on port ${port}`);
})

var todos = [];
var rid = 0;

app.use(bodyparser.json())

app.get("/todos", (req,res) => {
    res.status(200).send(todos)
})

app.post("/todos", (req,res) => {
    let a = req.body
    a.id = rid++
    todos.push(a)
    res.status(201).send("your todo task added to the todo list with id:- " + (rid-1))
})

app.get("/todos/:id", (req,res) => {
    for(let i = 0; i<todos.length;i++)
    {
        if(todos[i].id == parseInt(req.params.id))
        {
            res.status(200).send(todos[i])
        }
    }
    res.status(404).send("There is no todo task with id:- "+parseInt(req.params.id))
})

app.put("/todos/:id", (req,res) => {
    let a = req.body
    for(let i = 0; i<todos.length;i++)
    {
        if(todos[i].id == parseInt(req.params.id))
        {
            a.id = parseInt(req.params.id)
            todos[i] = a
            res.status(200).send("Update successfull")
        }
    }
    res.status(404).send("There is no todo task with id:- "+parseInt(req.params.id))
})

app.delete("/todos/:id", (req,res) => {
    for(let i = 0; i<todos.length;i++)
    {
        if(todos[i].id == parseInt(req.params.id))
        {
            todos[i] = {}
            res.status(200).send("Deletion successfull")
        }
    }
    res.status(404).send("There is no todo task with id:- "+parseInt(req.params.id))
})

function defaul(req,res)
{
    res.status(404).send("Page not found")
}
app.get("/:example", defaul)
app.post("/:example", defaul)
app.put("/:example", defaul)
app.delete("/:example", defaul)



/*
This code stores the data in variables such as arrays
so when the program is stopped then all the data will be lost
we can avoid this by storing the data in files or databases
but for now let's work upon files 
the code for working with files will be available in index2.js file
Go to that file in this directory itself to learn more.
*/
